import type { NextPage } from "next";
import Head from "next/head";
import BlogCard from "../components/blog-card";

import { useGetBlogsDataQuery, BlogDetails } from "../store/blogs/blogs.api";

const Blogs: NextPage = () => {
  const blogsQueryResult = useGetBlogsDataQuery(null);
  const { data, isLoading } = blogsQueryResult;
  console.log(data);
  return (
    <div>
      <Head>
        <title>Blogs / el-ser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col pt-[10vh] justify-center items-center gap-y-8">
        <h1 className="text-color font-poppins text-5xl font-semibold pt-[5%]">
          Blogs
        </h1>
        {isLoading ? (
          <div>Still Loading</div>
        ) : (
          data.map((blog: BlogDetails) => {
            return <BlogCard key={blog._id} details={blog} />;
          })
        )}
      </main>
    </div>
  );
};

export default Blogs;
