import type { NextPage } from "next";
import Head from "next/head";
import { animated, useSpring } from "react-spring";
import Image from "next/image";

const Blogs: NextPage = () => {
  const spring = useSpring({
    from: {
      opacity: 0,
    },
    to: {
      opacity: 1,
    },
  });
  return (
    <div>
      <Head>
        <title>Blogs / el-ser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <section id="introduction-section" className=""></section>
      </main>
    </div>
  );
};

export default Blogs;
