import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>el-ser</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
      <main className="flex flex-col">
        <section
          id="introduction-section"
          className="h-screen w-screen flex justify-center items-center text-color"
        >
          <div id="image-container h-1/4 ">
            <Image
              src="/hero-pic.png"
              alt="hero shot"
              width="100%"
              height="100%"
            />
          </div>
          <div className="flex flex-col">
            <h1 className="font-poppins text-2xl md:text-4xl ">
              Hey there! I am
            </h1>
            <h2 className="font-lexendDeca font-bold text-6xl tracking-normal md:text-8xl">
              Manu
              <span className="text-navy-blue-400">el Ser</span>
              afin Bugarin
            </h2>
            <p className="font-poppins text-xl py-2 px-0 md:w-[95%] md:text-3xl">
              A software engineer, passionate in building amazing things
            </p>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
