import type { NextPage } from "next";
import { useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import { IParallax, Parallax, ParallaxLayer } from "@react-spring/parallax";

import { FaArrowCircleDown } from "react-icons/fa";

import heroImage from "../public/hero-pic.png";

const Home: NextPage = () => {
  const parallax = useRef<IParallax>(null);

  return (
    <>
      <Head>
        <title>el-ser</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
      <main>
        <Parallax ref={parallax} pages={3} style={{ top: "0", left: "0" }}>
          <ParallaxLayer
            offset={0}
            onClick={() => parallax.current?.scrollTo(1)}
            className="text-color"
          >
            <section
              id="hero-section"
              className="flex flex-col justify-center h-full w-full px-8 md:flex-row-reverse md:gap-8 md:items-center md:justify-around"
            >
              <div id="hero-text-container" className="flex flex-col">
                <h1 className="font-poppins text-2xl md:text-4xl">
                  Hey there! I am
                </h1>
                <h2 className="font-lexendDeca font-bold text-6xl tracking-normal md:text-8xl">
                  Manu
                  <span className="transition-theme text-teal-700 dark:text-teal-500">
                    el Ser
                  </span>
                  afin Bugarin
                </h2>
                <p className="font-poppins text-xl py-2 px-0 md:text-3xl">
                  Passionate in building amazing things
                </p>
              </div>
              <div
                id="hero-image-container"
                className="self-center max-w-xs md:max-w-sm"
              >
                <Image
                  id="hero-image"
                  src={heroImage}
                  alt="hero"
                  className="rounded-full"
                />
              </div>
            </section>
          </ParallaxLayer>

          {/* <ParallaxLayer sticky={{ start: 0, end: 3 }}>
            <FaArrowCircleDown className="transition-theme absolute right-0 bottom-0 w-12 h-12 mr-8 mb-8 animate-pulse-70 md:w-16 md:h-16" />
          </ParallaxLayer> */}

          <ParallaxLayer
            offset={1}
            speed={2.0}
            onClick={() => parallax.current?.scrollTo(2)}
            className="bg-cyan-300 dark:bg-cyan-900"
          >
            <section id="my-story" className="flex items-centerjustify-center">
              <p>my-story</p>
            </section>
          </ParallaxLayer>

          <ParallaxLayer
            offset={2}
            speed={1}
            onClick={() => parallax.current?.scrollTo(0)}
            className="text-color"
          >
            <section
              id="promotion"
              className="flex flex-col items-center justify-center"
            >
              <div>Check out my other stuff</div>
              <div className="flex">
                <button>Blogs</button>
                <button>Expereince</button>
              </div>
            </section>
          </ParallaxLayer>
        </Parallax>
      </main>
    </>
  );
};

export default Home;
