import type { NextPage } from "next";
import Head from "next/head";

import PageTitle from "../components/page-title";
import { useGetPublicRepositoriesQuery } from "../store/github/github.api";

const Work: NextPage = () => {
  const { data, isLoading, isError } = useGetPublicRepositoriesQuery(null);
  // console.log(isError);
  console.log(data);
  return (
    <div>
      <Head>
        <title>Experience / el-ser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col pt-[10vh] justify-center items-center gap-y-8">
        <PageTitle>Work</PageTitle>
      </main>
    </div>
  );
};

export default Work;
