import type { NextPage } from "next";
import Head from "next/head";

const Work: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Experience / el-ser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <section id="introduction-section" className=""></section>
      </main>
    </div>
  );
};

export default Work;
